### ISSUE TITLE
Can you provide a sample fragment of the input xml?

### ISSUE THREAD

**Issue by failable** [derrickturk/ocd_production#2]
Hi, I'm learning Rust and quick-xml and found you post helps a lot. I'm trying to download a xml copy but the website gives me a 502. Can you provide a sample fragment of the input XML? Thanks.

**Comment by derrickturk** [comment]
You should be able to reach it at ftp://164.64.106.6/Public/OCD/OCD%20Interface%20v1.1/volumes/wcproduction/wcproduction.zip

I'm not sure how often that IP changes, so the safest thing is probably to navigate from http://www.emnrd.state.nm.us/OCD/ocdonline.html to "Public FTP Server" and then follow the path above.
